server:
  port: 8181

spring:
  application:
    name: msg-service
  datasource:
    url: jdbc:mysql://localhost:3306/mylabs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      direct:
        acknowledge-mode: auto
    template:
      mandatory: true
    # publisher-confirms：设置为true时。当消息投递到Exchange后，会回调confirm()方法进行通知生产者
    # publisher-returns：设置为true时。当消息匹配到Queue并且失败时，会通过回调returnedMessage()方法返回消息
    # spring.rabbitmq.template.mandatory: 设置为true时。指定消息在没有被队列接收时会通过回调returnedMessage()方法退回。
    # publisher-returns和mandatory如果都设置的话，优先级是以mandatory优先

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
