server:
  port: 8181

spring:
  application:
    name: msg-service
  datasource:
    url: jdbc:mysql://localhost:3306/mylabs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
