server:
  port: 8021

spring:
  application:
    name: cidea-server-pm
  main:
    allow-circular-references: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  # Elasticsearch 配置项
  elasticsearch:
    cluster-name: elasticsearch # 集群名
    cluster-nodes: 127.0.0.1:9300 # 集群节点
  datasource:
    url: jdbc:mysql://localhost:3306/mylab?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: CIdea
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: debug