server:
  port: 8070
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mylabs?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver