spring:
  datasource:
    url: jdbc:mysql://192.168.44.90:3306/ihp?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: ihp
    password: ihp
    driver-class-name: com.mysql.jdbc.Driver